include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: warning
    missing_return: warning

  plugins:
    - dart_code_metrics

  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.graphql.dart"
    - "**/*.graphql.g.dart"
    - "**/initializer.config.dart"
    - "**/generated"
    - "**/*.gr.dart"
    - "**/*.al.dart"
    - "**/*.i18n.dart"

dart_code_metrics:
  anti-patterns:
    - long-method
    - long-parameter-list
  metrics:
    cyclomatic-complexity: 20
    maximum-nesting-level: 5
    number-of-parameters: 4
    source-lines-of-code: 50
  metrics-exclude:
    - test/**
  rules:
    - avoid-missing-enum-constant-in-map
    - avoid-nested-conditional-expressions
    - avoid-throw-in-catch-block
    - avoid-unnecessary-type-casts
    - avoid-unused-parameters
    - avoid-unnecessary-type-assertions
    - binary-expression-operand-order
    - double-literal-format
    - no-boolean-literal-compare
    - no-empty-block
    - no-equal-then-else
    - no-object-declaration
    - prefer-correct-type-name
    - prefer-first
    - prefer-last
    - prefer-trailing-comma
    - always-remove-listener
    - avoid-returning-widgets
    - avoid-unnecessary-setstate
    - prefer-intl-name
    - provide-correct-intl-args
