name: edu_timetable_client
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  fpdart: ^0.0.14
  freezed_annotation: ^2.0.3
  intl: ^0.17.0
  retrofit: ^3.0.1+1
  shared_preferences: ^2.0.15

dev_dependencies:
  build_runner: ^2.1.11
  dart_code_metrics: ^4.15.2
  flutter_lints: ^1.0.0
  freezed: ^2.0.3+1
  index_generator: ^3.2.0+1
  json_serializable: ^6.2.0
  retrofit_generator: ^4.0.1

index_generator:
  exclude:
    - "**.g.dart"
    - "**.gr.dart"
    - "**.freezed.dart"
    - initializer.config.dart
  indexes:
    - path: lib/app

    - path: lib/core/domain
    - path: lib/core/infrastructure
    - path: lib/core/presentation

    - path: lib/modules/specialties/domain
    - path: lib/modules/specialties/infrastructure
    - path: lib/modules/specialties/presentation

    - path: lib/modules/timetable/domain
    - path: lib/modules/timetable/infrastructure
    - path: lib/modules/timetable/presentation

flutter:
  uses-material-design: true

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic

        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic

        - asset: assets/fonts/nunito/Nunito-Regular.ttf
          weight: 400
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
          weight: 400
          style: italic

        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic

        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic

        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic

        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
          style: italic
